prise_rendez_vous.rdv_config_entity.*:
  type: config_entity
  label: 'Rdv config entity config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    format_time:
      type: format_time
      label: 'Le format de durée ( minutes, heures, jours )'
    jours:
      type: mapping
      label: 'Liste de jour de la semaine'
    interval:
      type: integer
      label: "interval/durée d'un creneau"
    decalage:
      type: integer
      label: " Decallage entre deux creneaux"
    number_week:
      type: integer
      label: " Nombre de semaine à afficher "
    limit_reservation:
      type: integer
      label: " Nombre de reservation par creneaux "
    uid:
      type: integer
      label: " uid de l'utilisateur "
      
      
node.type.*.third_party.prise_rendez_vous:
  type: mapping
  label: 'Prise de RDV'
  mapping:
    prise_rendez_vous_enabled:
      type: boolean
      label: 'Whether to enable the reusable forms on this node type'